### ISSUE TITLE
[FEAT]: Implement Shape Drawing Tools

### ISSUE THREAD

**Issue by singodiyashubham87** [singodiyashubham87/Draw-it-out#33]
**Is your feature request related to a problem? Please describe.**
Users often need to draw geometric shapes like rectangles, circles, and lines, which can be time-consuming using freehand drawing tools.

**Describe the solution you'd like**
Add dedicated shape drawing tools to the toolbar, allowing users to easily create precise geometric shapes.

**Describe alternatives you've considered**
An alternative could be integrating a shape recognition algorithm, but manual shape drawing tools would offer more control.

**Additional context**
This feature would streamline the drawing process for users who frequently incorporate geometric shapes into their work.

**Comment by Prithwi32** [comment]
@singodiyashubham87 I would like to work on this issue under GSSOC'24

**Comment by AnantPatel1** [comment]
To allow users to draw shapes like rectangles, circles, and more we can create 
1:separate components for each shape you want to allow users to draw, like Rectangle, Circle, etc.
2: Implement event handlers to capture user input, such as mouse movements and clicks, to draw shapes on the canvas.
3:Use React state to keep track of the shapes drawn by the user.
4:Render the shapes based on the state onto the canvas.

An alternative approach could involve implementing a single versatile shape-drawing component that dynamically adjusts its behavior based on the user's selection. Instead of creating separate components for each shape, this component could accept parameters or configurations to determine the type of shape to draw (e.g., rectangle, circle, line) and the specific properties of that shape (e.g., position, size, color).

@singodiyashubham87 I'm excited to be a part of GSSOC'24 as a contributor and would like to work on this issue.

**Comment by singodiyashubham87** [comment]
@Prithwi32 Best of Luck!

**Comment by Prithwi32** [comment]
> @Prithwi32 Best of Luck!

@singodiyashubham87 Where shall I connect this project mentor and u, could please let me know discord server

**Comment by singodiyashubham87** [comment]
@Prithwi32 As of now, the mentors are not assigned the projects but will soon be assigned and there will be separate channel for each gssoc project in the server itself.
If you get any doubt before that then you can ask in the #general channel of GSSOC24 as we don't have other option.

**Comment by Prithwi32** [comment]
> @Prithwi32 As of now, the mentors are not assigned the projects but will soon be assigned and there will be separate channel for each gssoc project in the server itself. If you get any doubt before that then you can ask in the #general channel of GSSOC24 as we don't have other option.

Okay Thanks, I will connect u through LinkedIn

**Comment by singodiyashubham87** [comment]
@Prithwi32 Are you working on the issue or should I assign it to the next contributor?

**Comment by Prithwi32** [comment]
> @Prithwi32 Are you working on the issue or should I assign it to the next contributor?

@singodiyashubham87 I'm working on...Will try to complete by 2 days ...
I needed help actually as I'm new to this tech,

**Comment by singodiyashubham87** [comment]
@Prithwi32 You can ask your doubts on discord, Me & the mentors are there to help you out.

**Comment by Nandhinirameshmala** [comment]
I would like to work on it , please assign it to me

**Comment by singodiyashubham87** [comment]
@Nandhinirameshmala This issue is already resolved.
