### ISSUE TITLE
[FEAT] Resizeable Board

### ISSUE THREAD

**Issue by kailashchoudhary11** [singodiyashubham87/Draw-it-out#37]
As a user I should be able to draw larger things and the board should resize accordingly.

**Comment by singodiyashubham87** [comment]
@ayan-joshi Best of Luck!

**Comment by ayan-joshi** [comment]
> @ayan-joshi You are already been assigned an issue, kindly resolve it first before I can assign you any other issue.

ok sure I'm working on it , it will be done by tomorrow can start working on this after that

**Comment by ayan-joshi** [comment]
> > @ayan-joshi You are already been assigned an issue, kindly resolve it first before I can assign you any other issue.
> 
> ok sure I'm working on it , it will be done by tomorrow can start working on this after that @singodiyashubham87

**Comment by porwalshreyaa** [comment]
OK, I'll do this!

**Comment by singodiyashubham87** [comment]
@porwalshreyaa I have assigned the issue to you.
Best of Luck!

**Comment by porwalshreyaa** [comment]
@singodiyashubham87 
Is making Plus and Minus buttons to choose board size is okay? it looks like this when you click plus a bigger board appears (hence the drawing disappears, similar to what happens when you change background color) and same when you decrease the size.

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/111834212/706e9cf5-3dc7-4b2e-91f0-b2b9ef361b2b)

**Comment by singodiyashubham87** [comment]
@porwalshreyaa It's probably because when you are clicking on the + button it's re-rendering the whole canvas with new increased size and because of that render the previous draws are being cleaned up.

Do this instead: Store the drawings in an array, resize the canvas, redraw the drawing from the array

**Comment by porwalshreyaa** [comment]
> Do this instead: Store the drawings in an array, resize the canvas, redraw the drawing from the array

okay!

**Comment by riteshjha61253** [comment]
hey @singodiyashubham87 can you assign this issue to me. As I have knowledge of UI/UX, JS, HTML, CSS, and Tailwind. I can enhance the layout and styling.

**Comment by porwalshreyaa** [comment]
> @porwalshreyaa It's probably because when you are clicking on the + button it's re-rendering the whole canvas with new increased size and because of that render the previous draws are being cleaned up.
> 
> Do this instead: Store the drawings in an array, resize the canvas, redraw the drawing from the array

It's done, the only bug I am encountering is that it doesn't retain the bgcolor, let's me fix it and wrap up quickly!

**Comment by shubhammjha22** [comment]
@singodiyashubham87  can you assign this issue to me as well, as I'm working with @porwalshreyaa

**Comment by porwalshreyaa** [comment]
@shubhammjha22 why did you label it level 2 though, we are making a completely new feature naa? 😅

**Comment by singodiyashubham87** [comment]
@shubhammjha22 Assigned!
Best of Luck :)

**Comment by singodiyashubham87** [comment]
@porwalshreyaa There are various other factors too that we, as PAs need to consider while labelling the issues like approx. time taken, difficulty, etc.
& considering all those I made it level 2 issue.
But I think I should update the level considering the time & difficulty.
