### ISSUE TITLE
[Feature Request]: I want to add Contributors Page.

### ISSUE THREAD

**Issue by vishanurag** [singodiyashubham87/Draw-it-out#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- There should be a dedicated page, which will show the basic details of all the contributors of this project.

### Use Case

- Users can know, that how many people have worked on this project.

### Benefits

- We can showcase our contributors in a special webpage.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by vishanurag** [comment]
@singodiyashubham87 please assign this issue to me under GSSoC'24

**Comment by 0xabdulkhalid** [comment]
### Hi there @vishanurag 👋🏻 

You can't work on this issue right now, because adding Contributor's Page has been already addressed by @Varsani2520 on ISSUE #497.

Since this is a duplicate issue, I'm going to close this one. You can create a new issue addressing any other concerns. I'm looking forward to your contributions.

Thank you!

**Comment by vishanurag** [comment]
Ok 👍
